
if [[ -e $HOME/env/config/local/vars.zsh ]] ; then
  source $HOME/env/config/local/vars.zsh
fi

eval $(thefuck --alias)

export WRKSP=$HOME/env

source $WRKSP/dot/zsh/alias.zsh
source $WRKSP/dot/zsh/config.zsh
source $WRKSP/dot/zsh/environment.zsh
source $WRKSP/dot/zsh/functions.zsh
source $WRKSP/dot/zsh/path.zsh
source $WRKSP/dot/zsh/prompt.zsh


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


